### ISSUE TITLE
what happened to FileJar?

### ISSUE THREAD

**Issue by makhloughi** [adonisjs/bodyparser#32]
what happened to FileJar  reference in Adonis documentation https://adonisjs.com/docs/4.1/file-uploads#_multiple_file_uploads
link: https://github.com/adonisjs/adonis-bodyparser/blob/develop/src/Multipart/FileJar.js
does not exist.
and using multiple upload mode, returns object of undefined values! FileJar is missing.

**Comment by thetutlage** [comment]
The code in the `develop` branch is updated for v5. Here's the reference to the `FileJar` from version `2.0.9` https://github.com/adonisjs/bodyparser/blob/v2.0.9/src/Multipart/FileJar.js
