### ISSUE TITLE
Bodyparser breaking fresh installation of adonis 4.1

### ISSUE THREAD

**Issue by randygil** [adonisjs/bodyparser#43]
```
 randy@Samsung  ~/Devel  adonis new pruebaadonis --api-only --yarn
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___ 
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

  [1/6] 🔬  Requirements matched [node & npm]
  [2/6] 🔦  Ensuring project directory is clean [pruebaadonis]
  [3/6] 📥  Cloned [adonisjs/adonis-api-app]
  [4/6] 📦  Dependencies installed
  [5/6] 📖  Environment variables copied [.env]
  [6/6] 🔑  Key generated [adonis key:generate]

🚀   Successfully created project
👉   Get started with the following commands

$ cd pruebaadonis
$ adonis serve --dev

 randy@Samsung  ~/Devel  cd pruebaadonis 
 randy@Samsung  ~/Devel/pruebaadonis  adonis serve --dev

 SERVER STARTED 
> Watching files for changes...


Error: Cannot find module '@adonisjs/bodyparser/providers/BodyParserProvider'
Require stack:
- /home/randy/Devel/pruebaadonis/node_modules/require-stack/src/index.js
- /home/randy/Devel/pruebaadonis/node_modules/require-stack/index.js
- /home/randy/Devel/pruebaadonis/node_modules/@adonisjs/fold/src/Ioc/index.js
- /home/randy/Devel/pruebaadonis/node_modules/@adonisjs/fold/index.js
- /home/randy/Devel/pruebaadonis/server.js


1 requireStack
  /home/randy/Devel/pruebaadonis/node_modules/require-stack/src/index.js:44

2 anonymous
  /home/randy/Devel/pruebaadonis/node_modules/@adonisjs/fold/src/Registrar/index.js:104

3 arrayMap
  /home/randy/Devel/pruebaadonis/node_modules/lodash/lodash.js:653

4 Function.map
  /home/randy/Devel/pruebaadonis/node_modules/lodash/lodash.js:9622

5 interceptor
  /home/randy/Devel/pruebaadonis/node_modules/lodash/lodash.js:17094

6 thru
  /home/randy/Devel/pruebaadonis/node_modules/lodash/lodash.js:8859

Application crashed, make sure to kill all related running process, fix the issue and re-run the app
```

**Comment by thiagoarioli** [comment]
The problem is npm is installing the wrong version from body-parser, if you download the tag manually on GitHub you can compare and see the difference

**Comment by devalexandre** [comment]
> The problem is npm is installing the wrong version from body-parser, if you download the tag manually on GitHub you can compare and see the difference

I  was using version 12.16.3, now don`t work too

**Comment by dipedro** [comment]
In my case i'm using with adonis v4, for fix the problem, go to package.json:
“@adonisjs/bodyparser”: “^2.0.5"
remove the ^

**Comment by un-versed** [comment]
I fixed the problem using

`"@adonisjs/bodyparser": "~2.0.9",`

I don't know if this version is too old, but, it's the only version that worked for me (Since we prefixed the version with ~, NPM retrieved the latest patch version under the 2.0.9 minor version, which turned out to be 2.0.9 itself).

I hope they fix the docs soon

**Comment by thetutlage** [comment]
I am not sure why npm is installing the most recent version, coz the `package.json` file says `^2.0.5` 
 and the most recent version is targeted at v5. https://github.com/adonisjs/adonis-fullstack-app/blob/master/package.json#L21.

Lemme investigate and see if I can fix it

**Comment by HinNg** [comment]
Same problem here, building from docker image node:12.18.2-alpine3.12
Many thanks to @un-versed , using `"@adonisjs/bodyparser": "~2.0.9"` can fix the problem.

**Comment by devalexandre** [comment]
> Same problem here, building from docker image node:12.18.2-alpine3.12
> Many thanks to @un-versed , using `"@adonisjs/bodyparser": "~2.0.9"` can fix the problem.

I did it, and work too, thanks @un-versed

**Comment by vcarity** [comment]
> I fixed the problem using
> 
> `"@adonisjs/bodyparser": "~2.0.9",`
> 
> I don't know if this version is too old, but, it's the only version that worked for me (Since we prefixed the version with ~, NPM retrieved the latest patch version under the 2.0.9 minor version, which turned out to be 2.0.9 itself).
> 
> I hope they fix the docs soon

Same issue, bodyparser dependency broke azure pipeline. Applied suggested change, its working again.
Thanks a lot.

**Comment by thetutlage** [comment]
Has been fixed
