### ISSUE TITLE
maxFieldsSize 2097152 exceeded

### ISSUE THREAD

**Issue by CreatorB** [adonisjs/bodyparser#51]
### Discussed in https://github.com/adonisjs/core/discussions/3231

<div type='discussions-op-text'>

<sup>Originally posted by **freirejandre** October  8, 2021</sup>
hello, i'm having problems with the multipart/form-data limit and it seems the limit doesn't work
response from error 'PayloadTooLargeError  maxFieldsSize 2097152 exceeded'
my configs:
` multipart: {
    autoProcess: true,
    processManually: [],
    encoding: 'utf-8',
    convertEmptyStringsToNull: true,
    maxFields: 10000000,
    limit: '9999999999mb',
    types: ['multipart/form-data'],
}
<form action="/products" method="POST" enctype="multipart/form-data">
`

</div>

I've the same issue with my content field, it can have a base64/binary, I'm also modified config/bodyparser.ts but still got this error. Any help?

![image](https://user-images.githubusercontent.com/6529730/152261608-6fde1b92-82ec-42f1-8619-5ff8c5a47d10.png)

**Comment by thetutlage** [comment]
Seems like an issue with the fieldSize in bytes and not the number of fields. I will have to expose another configuration option for it.

**Comment by CreatorB** [comment]
Ah okay, thanks so much @thetutlage , can't wait for the next enhancement :)
