### ISSUE TITLE
AutoProcess is converting ".rvt" files to ".cfb"

### ISSUE THREAD

**Issue by HydraCOREY** [adonisjs/bodyparser#56]
When uploading a file:
```ts
const file = request.file("file")
```
The file is converted to the wrong file type.
Log:
```sh
fieldName: 'file',
  clientName: 'TestFile.rvt',
  headers: {
    'content-disposition': 'form-data; name="file"; filename="TestFile.rvt"',
    'content-type': 'application/octet-stream'
  },
  size: 59801600,
  errors: [],
  meta: {},
  state: 'consumed',
  extname: 'cfb',
  type: 'application',
  subtype: 'x-cfb',
  tmpPath: '/tmp/cl4rfvjj800008i0p76xf2pm1'
```

I can send you a test file. Github won't let me paste it in here.

## Package version
@adonisjs/bodyparser:
      "version": "8.1.3",

## Node.js and npm version
node: "16.14.2"
npm: "8.12.1"

Similar issue:
https://github.com/adonisjs/bodyparser/issues/53#issue-1216797748

**Comment by thetutlage** [comment]
Please upgrade to the latest of `@adonisjs/core@5.8.4`. The issue was fixed in https://github.com/adonisjs/bodyparser/releases/tag/v8.1.5
