### ISSUE TITLE
Cannot find module node_modules/strtok3/lib/index.js

### ISSUE THREAD

**Issue by munxar** [adonisjs/bodyparser#64]
### Package version

6.12.1

### Describe the bug

I set up a fresh project with `npm init adonisjs@latest hello-world` and tried to run it.
It currently result in an error when running certain commands e.g. `npm run dev` or `node ace repl`.
```bash
[ info ] starting HTTP server...
(node:35904) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

   Error: Cannot find module
   'xxx/hello-world/node_modules/strtok3/lib/index.js'
   imported from
   xxx/hello-world/node_modules/file-type/index.js
 

   ⁃ finalizeResolution
     node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
   ⁃ moduleResolve
     node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801
   ⁃ Object.defaultResolve
     node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912
```
I tried different node versions (20, 22), but the result is more or less the same.

The only thing that differs are the dependencies to `file-type`.

`npm ls strtok3` gives me this output:
```bash
└─┬ @adonisjs/core@6.12.1
  └─┬ @adonisjs/bodyparser@10.0.2
    └─┬ file-type@19.4.0
      └── strtok3@8.0.2
```

A project created a week ago that works without this error gives this dependencies:
```bash
└─┬ @adonisjs/core@6.12.1
  └─┬ @adonisjs/bodyparser@10.0.2
    └─┬ file-type@19.2.0
      └── strtok3@8.0.0
```

I think the problem is not with your package but with the subdependency from `file-type@19.4.0` to `strtok3@8.0.2`.
As a workaround I added strtok3@8.0.0 as a direct dependency with
`npm i strtok3@8.0.0` and everything works as before.

**Comment by thetutlage** [comment]
Can you try creating a new project and verify that is works? We have pinned the `strtok3` version to `8.0.1` since the author of the package has published incorrect file tree to npm

**Comment by munxar** [comment]
@thetutlage It works now when creating a new project. Thank you for the quick fix.

**Comment by filipnathanel** [comment]
For anyone encountering this on a non-empty project

to fix this I have :
- removed node_modules
- removed npm/yarn lock
- reinstalled dependencies

**Comment by RomainLanz** [comment]
> For anyone encountering this on a non-empty project
> 
> to fix this I have :
> 
>     * removed node_modules
> 
>     * removed npm/yarn lock
> 
>     * reinstalled dependencies

Instead of removing the `node_modules` and `lock` files, you can also directly ask your package manager to do a deep update of all your dependencies (nested one too).

```sh
npm update --save
```
