### ISSUE TITLE
Filename extension validation support

### ISSUE THREAD

**Issue by PPakalns** [adonisjs/bodyparser#9]
When uploading file, File class and [validation function](https://github.com/adonisjs/adonis-bodyparser/blob/develop/src/Multipart/File.js#L181) provides optional mime type validation.

But there are cases when mime type validation is not acceptable, e.g. when uploading CSV file, it can be recognized with many different mime types which is dependable on local user configuration. CSV file could be recognized as one of the following: text/csv, application/vnd.ms-excel, application/octet-stream etc.
Many files are recognized as application/octet-stream so enabling this mime type would allow users accidentally upload incorrect files.

It would be nice if support for filename extension validation could be added.

**Comment by borie88** [comment]
Can we add this feature to the docs?

**Comment by thetutlage** [comment]
Mind creating a PR for same?

**Comment by borie88** [comment]
Just trying to now, but it seems like I can't build the docs on Windows. npm run setup fails at ./ace build:docs, saying **'.' is not recognized as an internal or external command,
operable program or batch file.** at ./ace build:docs... Can't open an issue on the docs repo either
